feat: SHA256
openvm-org/openvm pull request #1022
Opened 2024-12-12 22:10 UTC by arayikhalatyan

Resolves INT-1726
Resolves INT-1748
Resolves INT-2580

This PR implements the `Sha256` extension and `Sha256-Air` primitive.
Using interactions to constrain the message schedule turned out to be too inefficient (doing 34 interactions per row). Current implementation uses 470 columns x 17 rows = 7990 cells per block and does 17 interactions every row. I believe the chosen approach was indeed the best one among the 4 discussed options in the linear ticket.
The first 16 rows are round rows and the last one is a digest row. Reading the message happens in the first 4 rows of every block. Final hash computing happens on the 17th (digest) row of every block. Register reads and output write happens on the very last row of every message. The subair utilizes interactions with itself to constrain some values that are 'passed' from a digest row to the next digest row. The padding is completely handled by the Vm chip.

To compare with other implementations: halo2 uses about 7200 cells per block but they are able to access any row from local and not just the next. Also, they are allowing constraints up to degree 4. Considering the additional limitations our implementation does pretty well compared to the halo2's implementation.

Possible optimizations: It is possible to reduce the number of interactions by 8 per row by adding 16 columns (work var carries). I am not sure if this is worth doing after `GKR` changes?

---
Copilot generated:
This pull request introduces significant updates to the `Cargo.toml` files and the `Encoder` struct, as well as the addition of a new SHA256 implementation. The most important changes include adding new SHA256-related dependencies and modules, modifying the `Encoder` struct to include a new field, and implementing the SHA256 AIR (Algebraic Intermediate Representation) components.

### Dependency and Module Additions:
* [`Cargo.toml`](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R52-R54): Added new SHA256-related dependencies and modules, including `openvm-sha256-air`, `openvm-sha256-circuit`, `openvm-sha256-transpiler`, and `openvm-sha256-guest`. [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R52-R54) [[2]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R100) [[3]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R142-R144) [[4]](diffhunk://#diff-f43d2be11323bdce102d0733ead2bfde8104dd6f2fc3b4329c8a7eccda26c73bR19-R20)

### Encoder Struct Modifications:
* [`crates/circuits/primitives/src/encoder/mod.rs`](diffhunk://#diff-487c9ae9aa62421d845721cec6aea5e40a2c08e2c0afc4944fa129f9bf8ba39fR16): Added a new boolean field `reserve_invalid` to the `Encoder` struct and updated the constructor and methods to handle this new field. [[1]](diffhunk://#diff-487c9ae9aa62421d845721cec6aea5e40a2c08e2c0afc4944fa129f9bf8ba39fR16) [[2]](diffhunk://#diff-487c9ae9aa62421d845721cec6aea5e40a2c08e2c0afc4944fa129f9bf8ba39fL24-R25) [[3]](diffhunk://#diff-487c9ae9aa62421d845721cec6aea5e40a2c08e2c0afc4944fa129f9bf8ba39fR56) [[4]](diffhunk://#diff-487c9ae9aa62421d845721cec6aea5e40a2c08e2c0afc4944fa129f9bf8ba39fL89-R103)

### SHA256 AIR Implementation:
* [`crates/circuits/sha256-air/`](diffhunk://#diff-f301b73c0fa8b5e0f49bcaa0954048b2ffbd789ae5d3fb6b463764da20917e99R1-R29): Added a new module for SHA256 AIR implementation, including `Cargo.toml`, `lib.rs`, `columns.rs`, `mod.rs`, and `utils.rs` files. This includes defining the structure and functions necessary for the SHA256 AIR. [[1]](diffhunk://#diff-f301b73c0fa8b5e0f49bcaa0954048b2ffbd789ae5d3fb6b463764da20917e99R1-R29) [[2]](diffhunk://#diff-5c2789fdc229d07efcb151adb7123346d003d9e23511f681a3a58523d6657cd1R1-R4) [[3]](diffhunk://#diff-8e24175dbd7a43f79ff12b57ce4f38b3094ccbef6a69d242176799f539e7e3a4R1-R85) [[4]](diffhunk://#diff-fc21d0e54a07da526580d9f38c5a1074b11f802244c6801dfa4a01a71faf9bffR1-R8) [[5]](diffhunk://#diff-7334e26ae2dff8981bc324152301de417291046063697a5635f8d51495349132R1-R270)

### SDK Configuration Updates:
* [`crates/sdk/src/config/global.rs`](diffhunk://#diff-9e8f9d06a00fc68a4b25e2c46d1bf76f258449b99a4b2810cc48b68f391ed934R35-R36): Updated the SDK configuration to include SHA256 components in the `SdkVmConfig`, `SdkVmConfigExecutor`, and `SdkVmConfigPeriphery` enums, and modified the `impl SdkVmConfig` to support SHA256 transpiler extension. [[1]](diffhunk://#diff-9e8f9d06a00fc68a4b25e2c46d1bf76f258449b99a4b2810cc48b68f391ed934R35-R36) [[2]](diffhunk://#diff-9e8f9d06a00fc68a4b25e2c46d1bf76f258449b99a4b2810cc48b68f391ed934R51) [[3]](diffhunk://#diff-9e8f9d06a00fc68a4b25e2c46d1bf76f258449b99a4b2810cc48b68f391ed934R73-R74) [[4]](diffhunk://#diff-9e8f9d06a00fc68a4b25e2c46d1bf76f258449b99a4b2810cc48b68f391ed934R101-R102) [[5]](diffhunk://#diff-9e8f9d06a00fc68a4b25e2c46d1bf76f258449b99a4b2810cc48b68f391ed934R130-R132)

2024-12-17 06:34 UTC, jonathanpwang commented on crates/circuits/primitives/src/encoder/mod.rs
> +    pub fn new(cnt: usize, max_degree: u32, reserve_invalid: bool) -> Self {
update doc comments about `reserve_invalid` (invalid = dummy)

2024-12-17 06:35 UTC, jonathanpwang commented on crates/circuits/sha256-air/Cargo.toml
> +p3-poseidon2 = { workspace = true }
do we need these imports?

2024-12-17 06:35 UTC, jonathanpwang commented on crates/circuits/sha256-air/Cargo.toml
> +p3-poseidon2 = { workspace = true }
you can run `cargo machete` to check

2024-12-17 06:36 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/lib.rs
> +pub use sha256::*;
I think we can follow https://github.com/Plonky3/Plonky3/tree/main/keccak-air/src and just not have this folder (move stuff to `src`)

2024-12-17 20:37 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/sha256/air.rs
> +    bus_idx: usize,
```suggestion
    /// Internal bus for self-interactions in this AIR.
    bus_idx: usize,
```

2024-12-17 20:49 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/sha256/columns.rs
> +/// the first 16 rows of every SHA256 block will be of type Sha256RoundCols and the last row will be of type Sha256DigestCols
A comment somewhere around here about how a row in the air should either be transmuted to `Sha256RoundCols` vs `Sha256DigestCols` would be helpful

2024-12-17 21:04 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/sha256/utils.rs
> +/// TODO: make this as a method of [Encoder]
any reason not to just move these over to encoder now?

2024-12-18 05:08 UTC, jonathanpwang requested changes
Finished reviewing just sha256-air (not the VM part). The AIR constraints look correct and sound - I just have some comments & suggestions there to improve readability and make it easier to audit.

Two major requests:
1. The sha256-air crate has no standalone tests. All tests are in the VM part. It's best to have some tests in this crate to both show usage of the API and also so that we can unit test just this AIR without reliance on the VM part, which is important to catch potential errors in future refactors.
2. The trace generation needs to be refactored / slightly modified to ensure that we can easily parallelize trace generation across blocks. It is important that we don't need to single thread the trace generation of the entire matrix. It doesn't seem too big a change; you can handle padding blocks separately (but also potentially parallelized) and if necessary at the end modify the boundary row between non-padding and padding.

2024-12-18 05:08 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/sha256/trace.rs
> +    fn generate_carry_ae<F: PrimeField32>(
it feels like this has a lot of duplication with the work vars calculation and should ideally be inlined there -- is there a blocker?

2024-12-18 05:08 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/sha256/trace.rs
> +    pub fn generate_intermed_4<F: PrimeField32>(
this is not called in `generate_block_trace`! that makes the API overall hard to use and error-prone. also impacts parallelism.

2024-12-18 05:41 UTC, yi-sun commented
Let's also remember to add this to the book.

2024-12-19 02:18 UTC, jonathanpwang commented on docs/specs/ISA.md
> +| SHA256_RV32    | `a,b,c,1,2` | `[r32{0}(a):32]_2 = sha256([r32{0}(b)..r32{0}(b)+r32{0}(c)]_2)`. Does the necessary padding. Performs memory reads with block size `16` and writes with block size `32
Since a common use case is where you may need to hash the output of another hash, should we make input and output both use block size `16`?

2024-12-19 02:19 UTC, jonathanpwang commented on docs/specs/RISCV.md
> +| sha256      | R   | 0001011     | 111    | 0x0    | `[rd:32]_2 = sha256([rs1..rs1 + rs2]_2)` |
we could do funct3 = 100 and funct7 = 0x1?

2024-12-19 02:20 UTC, jonathanpwang commented on extensions/sha256/circuit/src/sha256_chip/air.rs
> +        self.sha256_subair.eval(builder, SHA256VM_CONTROL_WIDTH);
Ah all we need is to implement `InteractionBuilder` on `SubAirBuilder`. `SubAirBuilder` isn't a trait, it's just a struct.

2024-12-19 02:29 UTC, jonathanpwang commented on extensions/sha256/circuit/src/sha256_chip/mod.rs
> +const SHA256_WRITE_SIZE: usize = 32;
see previous comment about write size considerations to make it more compatible with potential input into another hash

2024-12-31 07:41 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/trace.rs
> +    /// This function takes the input_massage (should be already padded), the previous hash,
```suggestion
    /// This function takes a 512-bit chunk of the input message (padding not handled), the previous hash,
```

2024-12-31 07:42 UTC, jonathanpwang commented on crates/circuits/sha256-air/src/trace.rs
> +    /// Note that, some values cannot be correctly generated at this time, refer to [`generate_missing_cells`] for details
```suggestion
    /// **Note**: this function only generates some of the required trace. Another pass is required, refer to [`generate_missing_cells`] for details.
```

2024-12-31 08:35 UTC, jonathanpwang approved these changes
lgtm

2024-12-31 08:49 UTC, merged