[feat] support weiestrass curve, add p256
openvm-org/openvm pull request #1107
Opened 2024-12-17 00:47 UTC by luffykai

fix INT-2594
fix INT-2583

- [ ] right now proving fails....

2024-12-17 01:04 UTC, luffykai commented on extensions/ecc/guest/src/p256.rs
> +        // heuristic
rm?

2024-12-17 01:05 UTC, luffykai commented on crates/toolchain/tests/src/ecc_tests.rs
> +    let p = openvm_ecc_guest::p256::P256_MODULUS.clone();
rm

2024-12-17 18:03 UTC, yi-sun commented
@luffykai -- this PR should also update the book accordingly

2024-12-18 23:49 UTC, luffykai commented on crates/circuits/mod-builder/src/README.md
> +## Notes on flags and setup
https://linear.app/intrinsictech/issue/INT-2907/simplyunify-the-expr-builder-to-all-have-setup

2024-12-18 23:53 UTC, jonathanpwang commented on extensions/ecc/circuit/Cargo.toml
> +    "k256",
actually I don't think it needs either `k256` or `p256`, it only needed `halo2curves`

2024-12-18 23:54 UTC, jonathanpwang commented on extensions/ecc/circuit/src/weierstrass_extension.rs
> +pub static P256_CONFIG: Lazy<CurveConfig> = Lazy::new(|| CurveConfig {
huh actually its a little weird these were here instead of in their modules. if it's minimal refactor, move into `p256`

2024-12-18 23:55 UTC, jonathanpwang commented on extensions/ecc/circuit/src/weierstrass_extension.rs
> +pub static P256_CONFIG: Lazy<CurveConfig> = Lazy::new(|| CurveConfig {
(actually where are we using either of these configs at all?)

2024-12-18 23:58 UTC, jonathanpwang commented on extensions/ecc/guest/src/p256.rs
> +    // TODO: msm optimization if needed
p256 has prime order, so you can copy the same implementation stuff from k256

2024-12-19 00:25 UTC, jonathanpwang requested changes
`SETUP_SW_DOUBLE` now needs to read `CURVE_A` from memory and constrain it for security.

Something to watch out for in the chip: since we only read two field elements from memory, we'll need to use the "y" coordinate to read `CURVE_A`. However the other constraints currently don't allow y == 0 (mod p), whereas we can have `a == 0`, so the constraints might need to be adjusted.

cc @Golovanov399

2025-01-06 13:39 UTC, luffykai commented on crates/circuits/mod-builder/src/core_chip.rs
> +            .flat_map(|&i| vars[i].clone())
nice... is there tip for this kind of optimization or just experience? I think even with AI I still got to more verbose solutions a lot of time.

2025-01-06 14:04 UTC, luffykai commented on crates/circuits/mod-builder/src/README.md
> +- EcDouble for Weierstrass curve (not short Weierstrass ones): `y^2 = x^3 + ax + b` where `a != 0`. Last valid row with `is_valid = 0` won't work as in that case `setup = is_valid - sum(all_flags) =
update: `y^2 = x^3 + ax + b` is "short weierstrass"

2025-01-06 15:42 UTC, luffykai commented on extensions/ecc/circuit/src/weierstrass_chip/double.rs
> +        let is_double_flag = builder.borrow_mut().new_flag();
i think even when it's setup, it still won't be 0 unless i misread it 🤔 so i think this is unnecessary. will check

2025-01-06 17:23 UTC, luffykai commented on extensions/ecc/circuit/src/weierstrass_chip/double.rs
> +        let is_double_flag = builder.borrow_mut().new_flag();
nvm i think we need it when setup is actually using a

2025-01-06 18:10 UTC, luffykai commented on crates/circuits/mod-builder/src/README.md
> +- EcDouble for Weierstrass curve (not short Weierstrass ones): `y^2 = x^3 + ax + b` where `a != 0`. Last valid row with `is_valid = 0` won't work as in that case `setup = is_valid - sum(all_flags) =
i think this is just wrong, we can't set the flags to 0 arbitrarily as the constraint won'y satisfy. but we don't this in the corechip now that double is not using it

2025-01-06 19:34 UTC, jonathanpwang commented on crates/circuits/mod-builder/src/core_chip.rs
> +            .flat_map(|&i| vars[i].clone())
I wouldn't call it an optimization heh. Just familiarity with the permutation of functions available

2025-01-06 19:35 UTC, jonathanpwang commented on crates/circuits/mod-builder/src/README.md
> +- EcDouble for Weierstrass curve (not short Weierstrass ones): `y^2 = x^3 + ax + b` where `a != 0`. Last valid row with `is_valid = 0` won't work as in that case `setup = is_valid - sum(all_flags) =
good catch, please update

2025-01-06 19:59 UTC, luffykai commented on extensions/ecc/circuit/src/weierstrass_extension.rs
> +pub static P256_CONFIG: Lazy<CurveConfig> = Lazy::new(|| CurveConfig {
it's here so guest doesn't dependent on circuit? The extension and `CurveConfig` are in circuit crate

2025-01-06 20:07 UTC, luffykai commented on extensions/ecc/sw-setup/src/lib.rs
> +                        struct_path
the extern function name is changed from using coord type to point type. I think it's fine

2025-01-08 08:34 UTC, jonathanpwang commented
can you resolve merge conflict?

2025-01-08 15:25 UTC, luffykai commented
> can you resolve merge conflict?

done

2025-01-08 21:54 UTC, jonathanpwang approved these changes
LGTM

2025-01-08 21:55 UTC, merged